### PR TITLE
Data Analysis on Air Quality of India

### PR DESCRIPTION
**Pull request by krishnasharma1386**

### CODE REVIEW

**Comment by krishnasharma1386** [comment]
This is my first project of Data Analysis

**Comment by lakshyatyagi24** [comment]
Please attach the screenshot or screen recording of output of your project

**Comment by krishnasharma1386** [comment]
Screenshot (119)
Screenshot (120)
Screenshot (121)
Screenshot (122)
Screenshot (123)
Screenshot (124)
Screenshot (125)
Screenshot (126)
Screenshot (127)
Screenshot (128)
Screenshot (129)
Screenshot (130)
Screenshot (131)
Screenshot (132)
Screenshot (133)
Screenshot (134)
Screenshot (135)
Screenshot (136)

**Comment by krishnasharma1386** [comment]
Lakshya bhiya rather than this should I attach a pdf of output or link of my project

**Pull request merged**
