### PR TITLE
Adventure_game.py

### PR DESCRIPTION
**Pull request by jcovington16**
Changed a few things to help the reader read the information better and also added the option for the use to exit out of the game if they wanted to with an graceful exit

### CODE REVIEW

**Comment by akanksha-raghav** [comment]
Please push your code to the repo and not all the files

**Comment by jcovington16** [comment]
Oh snap. I understand, my apologies. Pushing my changes now.

**Comment by jcovington16** [comment]
My apologies. I thought I pushed just the file. I pushed only the file this go around.

**Comment by akanksha-raghav** [comment]
> My apologies. I thought I pushed just the file. I pushed only the file this go around.

Create another pull request as there are 176 files changed in this one

**Pull request closed without merging**
